# AR parameters such as FFT parameters.
audio_repr: ar_ast_ext.AR_AST_Fusion
weight_file: external/ast/pretrained_models/ast_audioset.pth
feature_d: 768
sample_rate: 16000
n_fft: 400
window_size: 400
hop_size: 160
n_mels: 128
window: hanning

# Training parameters. Blackbox: linear evaluation, whitebox: end-to-end training.
batch_size: 128
lr_lineareval: 0.0003
lr_finetune_frozen: 0.001
lr_finetune_finetune: 0.00003
report_per_epochs: 20
early_stop_epochs: 20

# Model specific parameters.
ast_layers: [4, 11]
