# AR parameters such as FFT parameters.
audio_repr: ar_cnn14_ext.AR_Cnn14_Fusion
feature_d: 2048
sample_rate: 16000
n_fft: 512
window_size: 512
hop_size: 160
n_mels: 64
f_min: 50
f_max: 8000
temporal_pooling_type: mean_max

# Training parameters. Blackbox: linear evaluation, whitebox: end-to-end training.
batch_size: 256
lr_lineareval: 0.0003
lr_finetune_frozen: 0.0003
lr_finetune_finetune: 0.0003
report_per_epochs: 20
early_stop_epochs: 20

# Model specific parameters.
cnn14_layers: [3, 6]
